name: geomag
description: Translate GPS location data to geo-magnetic data such as magnetic declination.
version: 0.2.1
homepage: https://github.com/jifalops/geomag

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  intl: ^0.19.0
  meta: ^1.15.0

dev_dependencies:
  flutter_lints: ^5.0.0
  test: ^1.25.14